### PR TITLE
dont build TRIQS >3.0 storage

### PR DESCRIPTION
**Pull request by thenoursehorse**
Newer versions of TRIQS changed arrays to TRIQS/nda, so there is no need for this backend anymore. To keep compatibility with older code, check the TRIQS version in cmake, warn, and skip building the tests/examples for TRIQS.

### CODE REVIEW

**Comment by krivenko** [comment]
Dear @thenoursehorse,

Thank you for pointing this out. Indeed, the `arrays` framework is available only in a limited range of TRIQS library releases. I would, however, take a slighly different approach to fixing this issue. Instead of checking the version after the fact, one can pass a range of acceptable versions to `find_package()`. Let me update this PR accordingly.

**Comment by thenoursehorse** [comment]
Hi @krivenko,

Thanks for looking into this. I'm not sure that using a range for `find_package` works for TRIQS, because they may not have set up their `TRIQSConfig-version.cmake` to work with ranges. From the [cmake manual](https://cmake.org/cmake/help/latest/command/find_package.html#config-mode-version-selection) it specifies that when a range of versions is given, it essentially sets `PACKAGE_FIND_VERSION` to the minimum version in the range for backwards compatability. The TRIQS version checking only uses this variable, instead of the `PACKAGE_FIND_VERSION_MIN` and `PACKAGE_FIND_VERSION_MAX` variables.

This is the contents of `TRIQSConfig-version.cmake`, last modified 6 yeas ago:

```cmake
set(PACKAGE_VERSION 3.2.0)

if (PACKAGE_FIND_VERSION VERSION_EQUAL PACKAGE_VERSION)
 set(PACKAGE_VERSION_EXACT TRUE)
endif()

if (PACKAGE_FIND_VERSION VERSION_LESS PACKAGE_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

if (PACKAGE_FIND_VERSION VERSION_GREATER PACKAGE_VERSION)
 set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

A fix is to have TRIQS update their cmake config to work with ranges, but then using version ranges in `find_package` for TRIQS 3.1 will still work incorrectly. That was my motivation for checking the version after `find_package` incorrectly finds the wrong version. I confess, if TRIQS changes their cmake version check, this is an incredibly niche scenario that probably will never happen!

For reference, this is what the `TRIQSConfig-version.cmake` file needs to include to work with ranges

```cmake
if (PACKAGE_FIND_VERSION_MAX VERSION_LESS PACKAGE_VERSION)
 set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()

if (PACKAGE_FIND_VERSION_MIN VERSION_GREATER PACKAGE_VERSION)
 set(PACKAGE_VERSION_UNSUITABLE TRUE)
endif()
```

(or at least, just the first check against the max range).

**Comment by krivenko** [comment]
> A fix is to have TRIQS update their cmake config to work with ranges, but then using version ranges in find_package for TRIQS 3.1 will still work incorrectly. That was my motivation for checking the version after find_package incorrectly finds the wrong version. I confess, if TRIQS changes their cmake version check, this is an incredibly niche scenario that probably will never happen!

My bad, I got overly excited and naively expected things to just work.

Anyhow, I have reverted a couple of my commits and checked that finding TRIQS 3.1/3.2 disables compilation of triqs unit tests and examples.

**Comment by thenoursehorse** [comment]
No problems. I should have been clearer in my original PR about why I chose to check the version that way.

Thanks for all the hard work and great piece of code!

**Pull request merged**
